server:
  port: 9002
spring:
  application:
    name: user
  rabbitmq:
    host: 192.168.10.62
    username: told
    password: 111111
    port: 5672
management:
  security:
    enabled: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
env: dev1
